package com.vahak.parentcontroll.ui.theme

import androidx.compose.ui.graphics.Color

data class CustomColors(
    val primary: Color,
    val primaryVariant: Color,
    val secondary: Color,
    val background: Color,
    val surface: Color,
    val cardInnerBG: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textHint: Color,
    val divider: Color,
    val bottomNavigationBG: Color,
    val iconColor: Color,
    val green: Color,
    val greenLight: Color,
    val red: Color,
    val redLight: Color,
    val blue: Color,
    val yellow: Color,
    val orange: Color,
    val orangeLight: Color,
    val indicatorSelected: Color,
    val indicatorUnSelected: Color,
    val backgroundCardTeal: Color,
    val backgroundCardBlue: Color,
    val backgroundCardYellow: Color,
    val backgroundCardRed: Color,
    val backgroundButtonDisable: Color,
)

data class LightColors(
    val primary: Color = Color(0xFF00B09B),
    val primaryVariant: Color = Color(0xFF00897B),
    val secondary: Color = Color(0xFF96C93D),
    val background: Color = Color(0xFFF4F7F6),
    val surface: Color = Color(0xFFFFFFFF),
    val cardInnerBG: Color = Color(0xFFE0F2F1),
    val textPrimary: Color = Color(0xFF2C3E50),
    val textSecondary: Color = Color(0xFF7F8C8D),
    val textHint: Color = Color(0xFFAAB2B3),
    val divider: Color = Color(0xFFE0E0E0),
    val bottomNavigationBG: Color = Color(0xFFFFFFFF),
    val iconColor: Color = Color(0xFF00B09B),
    val green: Color = Color(0xFF00B09B),
    val greenLight: Color = Color(0xFFF0FDF4),
    val red: Color = Color(0xFFFF5858),
    val redLight: Color = Color(0xFFFFEBEE),
    val blue: Color = Color(0xFF4FACFE),
    val yellow: Color = Color(0xFFFFC107),
    val orange: Color = Color(0xFFF57C00),
    val orangeLight: Color = Color(0xFFFFE0B2),
    val indicatorSelected: Color = Color(0xFF00B09B),
    val indicatorUnSelected: Color = Color(0xFFCFD8DC),
    val backgroundCardTeal: Color = Color(0xFF00B09B),
    val backgroundCardBlue: Color = Color(0xFF4FACFE),
    val backgroundCardYellow: Color = Color(0xFFFFC107),
    val backgroundCardRed: Color = Color(0xFFFF5858),
    val backgroundButtonDisable: Color = Color(0xFFBDBDBD)
)

data class DarkColors(
    val primary: Color = Color(0xFF4DB6AC),
    val primaryVariant: Color = Color(0xFF00796B),
    val secondary: Color = Color(0xFFAED581),
    val background: Color = Color(0xFF121212),
    val surface: Color = Color(0xFF1E1E1E),
    val cardInnerBG: Color = Color(0xFF263238),
    val textPrimary: Color = Color(0xFFFFFFFF),
    val textSecondary: Color = Color(0xFFB0BEC5),
    val textHint: Color = Color(0xFF78909C),
    val divider: Color = Color(0xFF373737),
    val bottomNavigationBG: Color = Color(0xFF1E1E1E),
    val iconColor: Color = Color(0xFF4DB6AC),
    val green: Color = Color(0xFF81C784),
    val greenLight: Color = Color(0xFF1B2E1D),
    val red: Color = Color(0xFFEF5350),
    val redLight: Color = Color(0xFF3E2723),
    val blue: Color = Color(0xFF64B5F6),
    val yellow: Color = Color(0xFFFFD54F),
    val orange: Color = Color(0xFFFFB74D),
    val orangeLight: Color = Color(0xFF4E342E),
    val indicatorSelected: Color = Color(0xFF4DB6AC),
    val indicatorUnSelected: Color = Color(0xFF455A64),
    val backgroundCardTeal: Color = Color(0xFF00796B),
    val backgroundCardBlue: Color = Color(0xFF1976D2),
    val backgroundCardYellow: Color = Color(0xFFFBC02D),
    val backgroundCardRed: Color = Color(0xFFD32F2F),
    val backgroundButtonDisable: Color = Color(0xFF37474F)
)