package com.vahak.mehrban.core.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

enum class NotificationType {
    NEWS, ALERT, SYSTEM, REPORT
}

@Entity(tableName = "notifications")
data class NotificationEntity(
    @PrimaryKey
    val id: String = UUID.randomUUID().toString(), // 🚀 UUID prevents Local vs Remote collisions

    @ColumnInfo(name = "child_id")
    val childId: String? = null,

    val title: String,
    val message: String,

    @ColumnInfo(name = "type")
    val type: NotificationType,

    @ColumnInfo(name = "is_read")
    val isRead: Boolean = false,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),

    // 🚀 If true, this was generated by the app (e.g., time limit) and backend doesn't know about it
    @ColumnInfo(name = "is_local_only")
    val isLocalOnly: Boolean = false,

    // 🚀 If true, the backend knows we have read this message
    @ColumnInfo(name = "is_synced")
    val isSynced: Boolean = true
)